INCLUDE "src/txt/dialog/special.asm"
INCLUDE "src/txt/dialog/char.asm"
INCLUDE "src/txt/dialog/text.asm"
INCLUDE "src/txt/dialog/dialog.asm"
INCLUDE "src/txt/tilemap/tilemap.asm"
INCLUDE "src/txt/font/font.asm"
